# Generated by Django 2.1.15 on 2020-09-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=18, default=28.0289837, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=18, default=1.6666663, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('familyname', models.CharField(blank=True, max_length=50, null=True)),
                ('demand', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('typevehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('familyname', models.CharField(blank=True, max_length=50, null=True)),
                ('certifications', models.ManyToManyField(to='vrp.Certification')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField(default=0)),
                ('typevehicle', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Address')),
                ('destinations', models.ManyToManyField(to='vrp.Customer')),
                ('typecertification', models.ManyToManyField(to='vrp.Certification')),
            ],
        ),
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valide', models.BooleanField()),
                ('sizepopulation', models.IntegerField()),
                ('generationnumber', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('point_list', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Address')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drivers', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_end', to='vrp.Address')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_start', to='vrp.Address')),
                ('stops', models.ManyToManyField(to='vrp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('registrationnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=0, help_text='vehicle load')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('route_inding_indice', models.IntegerField(default=0)),
                ('customers', models.ManyToManyField(to='vrp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicles',
            field=models.ManyToManyField(to='vrp.Vehicle'),
        ),
        migrations.AddField(
            model_name='route',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Tour'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.Vehicle'),
        ),
        migrations.AddField(
            model_name='planification',
            name='tours',
            field=models.ManyToManyField(to='vrp.Tour'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'sequence')},
        ),
    ]
