# Generated by Django 2.1.15 on 2020-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planification',
            name='generationnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planification',
            name='sizepopulation',
            field=models.IntegerField(default=0),
        ),
    ]
